//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Due�o.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.modelo;

import java.util.ArrayList;
import java.util.List;

public class Dueno extends Usuario {
    private List<Mascota> listaMascotas;

    public Dueno(String id, String nombre, EnumProveedor proveedor) {
        super(id, nombre, proveedor);
        listaMascotas = new ArrayList<>();
    }

    public void addMascota(Mascota mascota) {
        listaMascotas.add(mascota);
    }

    public List<Mascota> getListaMascotas() {
        return listaMascotas;
    }

    public void setListaMascotas(List<Mascota> listaMascotas) {
        this.listaMascotas = listaMascotas;
    }

    @Override
    public String toString() {
        return String.format("%s;%s;%s;%s", nombre, id, proveedor, getClass().getSimpleName());
    }
}
