//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Mascota.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//
package org.example.modelo;

import java.util.ArrayList;
import java.util.List;

public class Mascota {
    private String riac;
    private int poliza;
    private String nombre;
    private String localidad;
    private String descripcion;
    private Dueno dueno;
    private List<Cuidado> listaCuidados;

    public Mascota(String riac, int poliza, String nombre, String localidad, String descripcion, Dueno dueno) {
        this.riac = riac;
        this.poliza = poliza;
        this.nombre = nombre;
        this.localidad = localidad;
        this.descripcion = descripcion;
        this.dueno = dueno;
        listaCuidados = new ArrayList<>();
        dueno.addMascota(this);
    }

    public String getRiac() {
        return riac;
    }

    public void setRiac(String riac) {
        this.riac = riac;
    }

    public int getPoliza() {
        return poliza;
    }

    public void setPoliza(int poliza) {
        this.poliza = poliza;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getLocalidad() {
        return localidad;
    }

    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Dueno getDueno() {
        return dueno;
    }

    public void setDueno(Dueno dueno) {
        this.dueno = dueno;
    }

    public void addCuidado(Cuidado cuidado) {
        listaCuidados.add(cuidado);
    }

    public List<Cuidado> getListaCuidados() {
        return listaCuidados;
    }

    public void setListaCuidados(List<Cuidado> listaCuidados) {
        this.listaCuidados = listaCuidados;
    }

    public String toString() {
        return String.format("%s;%s;%s;%s;%s;%s;%s", riac, poliza, nombre, localidad, descripcion, getClass().getSimpleName(), dueno.getId());
    }
}