//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MascotaExotica.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.modelo;

import java.io.File;

public class MascotaExotica extends Mascota {
    private File documentacion;

    public MascotaExotica(String riac, int poliza, String nombre, String localidad, String descripcion, Dueno dueno, File documentacion) {
        super(riac, poliza, nombre, localidad, descripcion, dueno);
        this.documentacion = documentacion;
    }

    public File getDocumentacion() {
        return documentacion;
    }

    public void setDocumentacion(File documentacion) {
        this.documentacion = documentacion;
    }
}
