//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaCuidador.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.vista;

import org.example.modelo.Cuidado;

import java.util.List;

public class VistaCuidador implements IVistaCuidador {

    public VistaCuidador() {
    }

    public void seleccionarCuidados(List<Cuidado> cuidados) {
        System.out.println(" -¿A qué mascota quieres cuidar? (Indicar número)");
        int num = 0;
        for (Cuidado c : cuidados) {
            num++;
            System.out.println(String.format("\t%s-Dueño: %s, mascota: %s, panchopuntos: %s", num, c.getMascota().getDueno().getNombre(), c.getMascota().getRiac(), c.getPanchopuntos()));
        }
    }

    public void tusCuidados(List<Cuidado> cuidados) {
        if (!cuidados.isEmpty()) {
            System.out.println(" -Tus Cuidados:");
            for (Cuidado c : cuidados) {
                System.out.println(String.format("\t-RIAC: %s, mascota: %s, fecha inicio: %s, fecha fin: %s, coste: %s, panchopuntos: %s", c.getMascota().getRiac(), c.getMascota().getNombre(), c.getFechaInicio(), c.getFechaFin(), c.getCoste(), c.getPanchopuntos()));
            }
        } else {
            throw new NullPointerException("No estas realizando ningún cuidado.");
        }
    }
}
