//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaMascota.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.vista;

public class VistaMascota implements IVistaMascota {
    public VistaMascota() {
    }

    public void mascotaRegistrada() {
        System.out.println(" -La mascota ha sido dada de alta con éxito.");
    }

    public void mascotaExoticaRegistrada() {
        System.out.println(" -La mascota exótica ha sido dada de alta con éxito.");
    }

    public void solicitarDatosMascota() {
        System.out.println(" -Introduzca los datos de la mascota (RIAC, nº póliza, nombre, localidad, descripción).");
    }
}