//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaDue�o.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.vista;

import org.example.modelo.Mascota;
import org.example.modelo.MascotaExotica;

import java.util.List;

public class VistaDueno implements IVistaDueno {

    public VistaDueno() {
    }

    public void listarMascotas(List<Mascota> mascotas) {
        if (!mascotas.isEmpty()) {
            System.out.println(" -Mascotas Registradas");
            for (Mascota m : mascotas) {
                if (m instanceof MascotaExotica)
                    System.out.println(String.format("\t-Dueño: %s, RIAC: %s, nº póliza: %s, nombre: %s, descripción: %s, dirección: %s, tipo: Mascota Exótica", m.getDueno().getNombre(), m.getRiac(), m.getPoliza(), m.getNombre(), m.getDescripcion(), m.getLocalidad()));
                else
                    System.out.println(String.format("\t-Dueño: %s, RIAC: %s, nº póliza: %s, nombre: %s, descripción: %s, dirección: %s, tipo: Mascota", m.getDueno().getNombre(), m.getRiac(), m.getPoliza(), m.getNombre(), m.getDescripcion(), m.getLocalidad()));
            }
        } else
            throw new NullPointerException("No dispones de ninguna mascota registrada.");
    }
}