//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : VistaUsuario.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.vista;

public class VistaUsuario implements IVistaUsuario {
    public VistaUsuario() {
    }

    public void usuarioCreado() {
        System.out.println(" -Usuario registrado correctamente.");
    }

    public void usuarioLogeado() {
        System.out.println(" -Usuario logeado correctamente.");
    }

    public void seleccionarProveedor() {
        System.out.println(" -Selecciona la red social con la que quieras hacer login (Google, Microsoft, Facebook, Twitter).");
    }

    public void seleccionarRol() {
        System.out.println(" -Selecciona el rol con el que quieras hacer login (Dueño, Cuidador).");
    }

    public void seleccionarNombre() {
        System.out.println(" -Introduzca su nombre de usuario.");
    }

    public void seleccionarTarifa() {
        System.out.println(" -Introduzca su tarifa como cuidador.");
    }

    public void seleccionarDescripcion() {
        System.out.println(" -Introduzca su descripción como cuidador.");
    }
}