//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorDueno.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.controlador;

import org.example.modelo.Dueno;
import org.example.vista.IVistaDueno;
import org.example.vista.VistaDueno;

public class ControladorDueno extends Controlador {
    private IVistaDueno vistaDueno;

    public ControladorDueno() {
        super();
        vistaDueno = new VistaDueno();
    }

    public void listarMascotasDueno() {
        Dueno dueno = (Dueno) interfazSistema.getUsuarioLogeado();

        vistaDueno.listarMascotas(dueno.getListaMascotas());
    }
}