//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ControladorCuidador.java
//  @ Date : 09/05/2024
//  @ Author : 
//
//

package org.example.controlador;

import org.example.modelo.Cuidado;
import org.example.modelo.Cuidador;
import org.example.vista.VistaCuidador;

import java.util.List;

public class ControladorCuidador extends Controlador {
    private VistaCuidador vistaCuidador;

    public ControladorCuidador() {
        super();
        vistaCuidador = new VistaCuidador();
    }

    // Métodos de GESTIÓN de PETICIONES de cuidado.
    public Cuidado listarMascotasCuidador(List<Cuidado> cuidados) {
        if (cuidados.isEmpty()) {
            throw new NullPointerException("No hay cuidados disponibles.");
        }

        try {
            vistaCuidador.seleccionarCuidados(cuidados);
            return cuidados.get(Integer.parseInt(interfazSistema.entradaString()) - 1);
        } catch (Exception e) {
            throw new IndexOutOfBoundsException("Indique un cuidado válido.");
        }
    }

    // Método de VISTA de cuidados de cada cuidador.
    public void verCuidados() {
        Cuidador cuidador = (Cuidador) interfazSistema.getUsuarioLogeado();

        vistaCuidador.tusCuidados(cuidador.getListaCuidados());
    }
}
